# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3623d77f56f411997540b3ea976b3c54c7fed9e8f0f67da3dc4fbda53030cf8ff1e67d833b50a0010d7820eaaa7d6ec62df1351f46cc49a9fcaa2fd39165a17

test:
  secret_key_base: 54134458937e2ebb51fe98dc886913fe266d8127f8332e72885eeed4757fcbb16642ab3f932fbd301703a6c28e4bfaf2fd7402138165cbc061c03d628a180b77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
